modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="echo_detectors"
version="${mod_version}"
displayName="Echo Detectors"
logoFile="echo_detectors_logo.png"
authors="Tortugolen"
description='''DETECTORS!!!'''

[[dependencies.echo_detectors]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.echo_detectors]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.echo_detectors]]
modId="ostrea"
mandatory=false
versionRange="${ostrea_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.echo_detectors]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="NONE"
side="CLIENT"
