modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="echo_detectors"
version="1.1.1.0"
displayName="Echo Detectors"
logoFile="echo_detectors_logo.png"
authors="Tortugolen"
description='''DETECTORS!!!'''

[[dependencies.ostrea]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ostrea]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ostrea]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="NONE"
side="CLIENT"
